# Generated by Django 3.2.7 on 2023-02-07 01:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('comment', models.TextField(null=True, verbose_name='コメント')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像5')),
                ('publicprivate', models.BooleanField(blank=True, choices=[(True, '公開'), (False, '非公開')], null=True, verbose_name='公開非公開')),
                ('publicname', models.CharField(blank=True, max_length=50, null=True, verbose_name='公開用ネーム')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'db_table': 'diary_info',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Talkchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('user_id', models.CharField(max_length=8, verbose_name='ユーザID')),
                ('user_type', models.CharField(max_length=1, verbose_name='ユーザタイプ')),
                ('image', models.CharField(max_length=256, null=True, verbose_name='画像')),
            ],
            options={
                'db_table': 'tc_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='主キー')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('datebirth', models.DateField(null=True, verbose_name='生年月日')),
                ('user_pass', models.CharField(max_length=10, verbose_name='ユーザパスワード')),
                ('telnum', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='半角数字のみを入力してください', regex='^[0-9]+$')], verbose_name='電話番号')),
                ('precycle', models.IntegerField(validators=[django.core.validators.MinValueValidator(8)], verbose_name='妊娠周期')),
                ('bloodtype', models.CharField(choices=[('A', 'A型'), ('B', 'B型'), ('AB', 'AB型'), ('O', 'O型')], max_length=2, null=True, verbose_name='血液型')),
                ('symptoms', models.CharField(max_length=100, null=True, verbose_name='症状')),
                ('user_type', models.CharField(max_length=1, verbose_name='ユーザタイプ')),
                ('hospitalname', models.CharField(max_length=50, null=True, verbose_name='病院名')),
                ('image1', models.ImageField(null=True, upload_to='', verbose_name='画像1')),
                ('image2', models.ImageField(null=True, upload_to='', verbose_name='画像2')),
                ('image3', models.ImageField(null=True, upload_to='', verbose_name='画像3')),
                ('image4', models.ImageField(null=True, upload_to='', verbose_name='画像4')),
                ('image5', models.ImageField(null=True, upload_to='', verbose_name='画像5')),
                ('last_login', models.DateTimeField(auto_now=True, max_length=8, verbose_name='最終ログイン')),
                ('comment', models.TextField(null=True, verbose_name='コメント')),
                ('egcontact', models.EmailField(max_length=254, null=True, verbose_name='緊急連絡先')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'db_table': 'User_info',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_meesages', to='precomi.room')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無し', max_length=255, verbose_name='名前')),
                ('comment', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='precomi.diary', verbose_name='対象記事')),
            ],
        ),
    ]
