# Generated by Django 3.2.7 on 2022-12-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precomi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='comment',
            field=models.TextField(null=True, verbose_name='コメント'),
        ),
    ]
