# Generated by Django 3.2.7 on 2022-12-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precomi', '0002_alter_diary_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='egcontact',
            field=models.EmailField(max_length=254, null=True, verbose_name='緊急連絡先'),
        ),
    ]
