# Generated by Django 3.2.7 on 2022-10-31 02:47

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('precomi', '0002_alter_user_precycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50, verbose_name='タイトル')),
                ('comment', models.CharField(max_length=100, null=True, verbose_name='コメント')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('image1', models.CharField(max_length=256, null=True, verbose_name='画像1')),
                ('image2', models.CharField(max_length=256, null=True, verbose_name='画像2')),
                ('image3', models.CharField(max_length=256, null=True, verbose_name='画像3')),
                ('image4', models.CharField(max_length=256, null=True, verbose_name='画像4')),
                ('image5', models.CharField(max_length=256, null=True, verbose_name='画像5')),
            ],
            options={
                'db_table': 'diary_info',
            },
        ),
        migrations.CreateModel(
            name='Talkchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('sex', models.CharField(max_length=1, verbose_name='性別')),
                ('user_id', models.CharField(max_length=8, verbose_name='ユーザID')),
                ('user_type', models.CharField(max_length=1, verbose_name='ユーザタイプ')),
                ('image', models.CharField(max_length=256, null=True, verbose_name='画像')),
            ],
            options={
                'db_table': 'tc_info',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodtype',
            field=models.CharField(max_length=2, null=True, verbose_name='血液型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='datebirth',
            field=models.DateTimeField(null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospitalname',
            field=models.CharField(max_length=50, null=True, verbose_name='病院名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image1',
            field=models.CharField(max_length=256, null=True, verbose_name='画像1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image2',
            field=models.CharField(max_length=256, null=True, verbose_name='画像2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image3',
            field=models.CharField(max_length=256, null=True, verbose_name='画像3'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image4',
            field=models.CharField(max_length=256, null=True, verbose_name='画像4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image5',
            field=models.CharField(max_length=256, null=True, verbose_name='画像5'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(max_length=8, verbose_name='最終ログイン'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='user',
            name='no',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='主キー'),
        ),
        migrations.AlterField(
            model_name='user',
            name='precycle',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(8)], verbose_name='妊娠周期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=1, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='user',
            name='symptoms',
            field=models.CharField(max_length=100, null=True, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telnum',
            field=models.CharField(max_length=12, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=8, verbose_name='ユーザID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pass',
            field=models.CharField(max_length=10, verbose_name='ユーザパスワード'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(max_length=1, verbose_name='ユーザタイプ'),
        ),
    ]
