# Generated by Django 3.2.7 on 2023-02-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precomi', '0002_message_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
