# Generated by Django 3.2.7 on 2023-01-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precomi', '0003_user_egcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='publicprivate',
            field=models.BooleanField(default=True),
        ),
    ]
