# Generated by Django 3.2.7 on 2023-02-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precomi', '0003_alter_room_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talkchat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hospitalname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_pass',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
