# Generated by Django 3.2.7 on 2023-01-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precomi', '0004_diary_publicprivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='publicprivate',
            field=models.BooleanField(choices=[(False, '非公開'), (True, '公開')], verbose_name='公開非公開'),
        ),
    ]
