# Generated by Django 3.2.7 on 2023-01-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precomi', '0005_alter_diary_publicprivate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='publicprivate',
            field=models.BooleanField(blank=True, choices=[(False, '非公開'), (True, '公開')], null=True, verbose_name='公開非公開'),
        ),
    ]
