# Generated by Django 3.2.7 on 2023-01-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precomi', '0007_alter_diary_publicprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='publicname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='公開用ネーム'),
        ),
    ]
