# Generated by Django 3.2.7 on 2022-10-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('datebirth', models.DateTimeField(null=True)),
                ('sex', models.CharField(max_length=1)),
                ('user_id', models.CharField(max_length=8)),
                ('user_pass', models.CharField(max_length=10)),
                ('telnum', models.CharField(max_length=12)),
                ('precycle', models.IntegerField(max_length=8)),
                ('bloodtype', models.CharField(max_length=2, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('user_type', models.CharField(max_length=1)),
                ('hospitalname', models.CharField(max_length=50, null=True)),
                ('image1', models.CharField(max_length=256, null=True)),
                ('image2', models.CharField(max_length=256, null=True)),
                ('image3', models.CharField(max_length=256, null=True)),
                ('image4', models.CharField(max_length=256, null=True)),
                ('image5', models.CharField(max_length=256, null=True)),
                ('last_login', models.DateTimeField(max_length=8)),
            ],
            options={
                'db_table': 'User_info',
            },
        ),
    ]
